<?php
namespace App\Notifications;
use App\Http\Controllers\Api\AuthController;
use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;
class VerifyEmailNotification extends Notification {
    public function via($n): array { return ['mail']; }
    public function toMail($n): MailMessage {
        // Reuses AuthController::verificationUrl() so the signed link this
        // email sends is generated by the exact same code the verify-email
        // endpoint checks against — one source of truth for the signing
        // logic instead of two implementations that could drift apart.
        $url = app(AuthController::class)->verificationUrl($n);
        return (new MailMessage)
            ->subject('Verify your EduBD email address')
            ->greeting("Hi {$n->name},")
            ->line('Welcome to EduBD! Please confirm your email address to activate your account.')
            ->action('Verify email address', $url)
            ->line('This link expires in 24 hours.')
            ->line("If you didn't create this account, you can safely ignore this email.");
    }
}
